### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/python#4]
@paulortman do you see any reason not to rename this to "python" instead of "python-pip"?

**Comment by paulortman** [comment]
No, "python" seems okay @davegaeddert .  If there is some other type of system to support it seems likely it _could_ be included in the future or else it also seems reasonable to have a different, more specific package, e.g. 'python-piptools'

I've never totally thought through the best way to go about renaming a project.  Is it to:
1) rename in GH
1) git remote delete|add
1) string substitute as necessary in project
1) rename local dev directory so as to not totally confuse oneself
1) rebuild virtualenv

**Comment by paulortman** [comment]
Closed by @davegaeddert
