### ISSUE TITLE
Additional files included in requirements.txt ("-r")

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/python#6]
Requirements.txt can include another file using `-r path`.

Currently, our collector ignores these (I think), so if you wanted to collect those, you'd have to do that separately. We should probably state that in the README.

dparse does provide the information though for us to do it automatically and include them as additional "manifests" (maybe an optional setting to disable it) -- [resolved_files](https://github.com/pyupio/dparse/blob/master/dparse/dependencies.py#L112)

**Comment by paulortman** [comment]
I've got this working I think.  @davegaeddert what's your sense for the defaults?  It seems to me that unlimited recursion is the most likely desired behavior.  What would you like to say that isn't that?  "no-recursion" "depth=1"

**Comment by davegaeddert** [comment]
Agree that unlimited recursion seems like it should be the default. Not sure on the other question...I guess my first thought would have been to just make it an enable/disable feature. It would seem fine to me though if it was something like `manifest_recursion_depth: 0` (1?) to disable it and give us the depth flexibility? Or `manifest_recursion: true|false|number`? That's maybe too ambiguous but I feel like true/false is going to be the most common, and if they want to specify depth then they could use a number?

**Comment by davegaeddert** [comment]
I'll close this for now, we can think about a setting if/when it comes up as a need.
