### ISSUE TITLE
AttributeError: 'PackageFinder' object has no attribute '_candidate_sort_key'

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/python#94]
```
Traceback (most recent call last):
  File "/usr/src/app/entrypoint.py", line 10, in <module>
    collect()
  File "/usr/src/app/collect.py", line 26, in collect
    output['manifests'][manifest.filename] = { 'current': { 'dependencies': manifest.dio_dependencies() } }
  File "/usr/src/app/models.py", line 89, in dio_dependencies
    'available': [{'name': x} for x in get_available_versions_for_dependency(dep.key, dep.specs)],
  File "/usr/src/app/models.py", line 195, in get_available_versions_for_dependency
    best_candidate = max(filtered_candidates, key=finder._candidate_sort_key)
AttributeError: 'PackageFinder' object has no attribute '_candidate_sort_key'
```
This is because `_candidate_sort_key` was removed with https://github.com/pypa/pip/commit/dddd28b8decd245f05a3678a3ad849c9e3a45456 in pip v19.1.

Relevant job: https://app.dependencies.io/j/c840a16a-3f83-4e90-859f-ed1fb686023a.

**Comment by davegaeddert** [comment]
Thanks so much for making the issue and adding the detail/links. I've pushed a fix. Would you mind running your repo again and making sure it works?

**Comment by Harmon758** [comment]
It seems to be working now, although pull requests weren't retroactively made for the updates that were missed.

**Comment by davegaeddert** [comment]
The pull requests get sent when it runs from the schedule, not every time you click the "check for updates" button. So if you've got it set to run daily, you should get those PRs tomorrow. Let me know if that doesn't happen or I'm missing something. Thanks again.

**Comment by Harmon758** [comment]
Ah, you're right, the scheduled run created the pull requests now.
Thanks for the fix.
